name: "Update Changelog"

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: "Update Changelog"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Project Repo"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: "Set Git Config"
        shell: bash
        run: |
          echo -e "machine github.com\n login ${{ secrets.PUSH_GITHUB_TOKEN }}" > ~/.netrc
          git config --global user.email "derek@derekperuo.net"
          git config --global user.name "dperuo"

      - name: "Update Changelog"
        shell: bash
        run: npx auto-changelog

      - name: "Commit Changes and Push"
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "(GitHub) Update changelog [skip-ci]"
            git push
          fi
